export const services = [
  "Todos", // always include this manually
  "Aula de inglês",
  "Professor Substituto",
  "Aula de Reforço",
  "Pedreiro",
  "Montador de Móveis",
  "Pintor Predial",
  "Pequenos Serviços Domésticos",
  "Marceneiro",
  "Serralheiro",
  "Eletricista",
  "Encanador",
  "Jardineiro",
  "Chaveiro",
  "Faxineira",
  "Babá",
  "Cuidador de Idosos",
  "Aulas de Música",
  "Instrutor de Yoga",
  "Personal Trainer",
  "Nutricionista",
  "Aulas de Natação",
  "Coach",
  "Designer Gráfico",
  "Programador",
  "Marketing Digital",
  "Fotógrafo",
  "Videomaker",
  "Tradutor",
  "Advogado",
  "Contador",
  "Outros",
];
